### ISSUE TITLE
Cannot get a "raw" value without the formatting

### ISSUE THREAD

**Issue by triggerjoi** [speccode/acf-price#7]
It's not possible to get a "raw" value without the formatting even if you were to send false in the `format_value` parameter in `get_field`. See the third parameter `$format_value` here https://www.advancedcustomfields.com/resources/get_field/.

I think it could be fixed by changing the `load_value` function in acf-price-common.php to `format_value` instead.

**Comment by speccode** [comment]
Thanks. Merged.
